spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iihtprojectmng?autoReconnect=true
    username: root
    password: pass@word1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8091





